language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get install coinor-cbc graphviz graphviz-dev pkg-config

install: "pip install -r travis_requirements.txt."
# command to run tests
script: nosetests --with-doctest
