language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

addons:
  apt:
    packages:
      - coinor-cbc

install:
  - pip install .
  - pip install coveralls

# command to run tests
script:
  - nosetests --with-doctest --with-coverage -c nose.cfg

after_success:
  - coveralls

